### ISSUE TITLE
Readme для клиента

### ISSUE THREAD

**Issue by dkeye** [dkeye/pixelwars_v2#4]
Описать в README все шаги от клонирования репозитория до запуска сервера в обоих случаях (dev и prod).

**Comment by dkeye** [comment]
Оформить README в соответствии с https://www.makeareadme.com/
Пример модно посмотреть в том же README для сервера

**Comment by dkeye** [comment]
Почитай как правильно пишутся комментарии к коммитам в интернета

**Comment by DimCore3** [comment]
https://slovarozhegova.ru/
